name: nineja_chat
description: "9jaChat - A modern TikTok clone for all platforms"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  animations: ^2.0.8
  lottie: ^3.0.0

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.9
  firebase_dynamic_links: ^5.4.17

  # Authentication
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3

  # Video & Media
  video_player: ^2.8.1
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  video_compress: ^3.1.2
  chewie: ^1.7.4
  path_provider: ^2.1.1
  permission_handler: ^11.0.1

  # Audio
  audioplayers: ^5.2.1
  just_audio: ^0.9.36

  # State Management
  provider: ^6.1.1
  get: ^4.6.6

  # Navigation
  auto_route: ^7.9.2

  # Networking
  http: ^1.1.2
  dio: ^5.4.0

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  timeago: ^3.6.1
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0

  # Push Notifications
  flutter_local_notifications: ^16.3.0

  # Chat & Messaging
  flutter_chat_ui: ^1.6.10
  emoji_picker_flutter: ^1.6.3

  # Image Processing
  image: ^4.1.3
  photo_view: ^0.14.0

  # Maps & Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Others
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^7.3.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

# Configuration for app icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

# Configuration for splash screen
flutter_native_splash:
  color: "#000000"
  image: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo.png
    color: "#000000"
  web: true

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/audio/
    - assets/config/

  # Fonts
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
